

PUT http://127.0.0.1:8000/api/advertisements/1/
Authorization: Token 6ce6eb7e452fe48ace67eb8bc9421527503f7e41
Content-Type: application/json

{
    "title": "Попытка взлома",
    "description": "Оригинальное описание",
    "price": "15000.00",  
    "status": "CLOSED"                    
}